### ISSUE TITLE
[BUG]:  Docker Fthelper connection Refused

### ISSUE THREAD

**Issue by genhack** [kamontat/fthelper#11]
# Bug report

## Describe the bug

When Ft helper start a warning appear and all request report with "Connection Refused". All config i try fail to connect fthelper to freqtrade.  No idea why he refuse to connect to the api. 

```
`18:03:31 freqtrade:connection [WARN ] | Get "http://127.0.0.1:8081/api/v1/show_config": dial tcp 127.0.0.1:8081: connect: connection refused
```
//Fix the problem
```
 -FTH_FREQTRADE__URL=http://freqtrade1:8081
```

**Comment by kamontat** [comment]
@genhack You should use `http://freqtrade1:8081` where `freqtrade1` is service name in **docker-compose.yml** file.
