### ISSUE TITLE
please show abs, pct coins by %

### ISSUE THREAD

**Issue by lorvent** [kamontat/fthelper#13]
Hello,
currently freqtrade_pair_performance_profit_pct and freqtrade_pair_performance_profit_abs returns coins list alphabetically,
is it possible to show in descending order as we see in frequi Performance tab?

thanks,

**Comment by kamontat** [comment]
This is depend on grafana. But stay tune, new Grafana dashboard will have this feature. I will upload it within today.
At https://grafana.com/grafana/dashboards/14632

<img width="1061" alt="CleanShot 2021-08-01 at 17 40 19@2x" src="https://user-images.githubusercontent.com/14089557/127767897-2b9c1376-6cd9-4bd5-a8e9-221f8bbb6b8c.png">

**Comment by kamontat** [comment]
Released as `v4.5.0`
