### ISSUE TITLE
[feature]: Daily stats and monthly stats

### ISSUE THREAD

**Issue by lorvent** [kamontat/fthelper#15]
Hello,
Like we see in "daily" tab in freqUI, can we see daily stats here in this aswell?

either a table or a bar chart/graph?

i tried `freqtrade_perf_daily` but it says `Empty query result` in prom graph UI

and I am not able to make it work with grafana.

Would be great, if you can add a daily bar chart and monthly bar chart.

thanks :)

**Comment by kamontat** [comment]
For daily, it will collect at midnight. So if you run more then 1 day, the data will show.

**Comment by kamontat** [comment]
For monthly, I will add today.

**Comment by lorvent** [comment]
> For daily, it will collect every midnight. So you need to run more than 1 day, the data will show.

Hello, I am running for more than a week still it doesn't display properly, may be i am doing something wrong.



> For monthly, I will add soon if I have time..

Thanks :)

**Comment by kamontat** [comment]
Please check on log, you should see this message.
https://github.com/kamontat/fthelper/blob/21fbcbe56707cdad593d2329295d148d433fed31/metric/src/freqtrade/warmup_daily_performance.go#L22

When It fetching balance to compare.
