### ISSUE TITLE
[feature]: include used exchange in freqtrade status

### ISSUE THREAD

**Issue by fmhc** [kamontat/fthelper#16]
(talking about the metrics part) Is it possible to show the exchange within the collected data like the strategy?
And another topic: can we have the output of show_config somewhere? 
This would be great for "live-debugging" / using that data for further stuff...
Would like to give it a try to contribute here something, but you're so fast with releasing improvements - currently i'm using v5.3.0, will upgrade soon

**Comment by kamontat** [comment]
> Is it possible to show the exchange within the collected data like the strategy?

Which information did you want? Currently, I already expose strategy name from `show_config` endpoint.

**Comment by kamontat** [comment]
> can we have the output of show_config somewhere?

I did export information from `show_config` here.

Data part: 
https://github.com/kamontat/fthelper/blob/5fffff176844aa92c48febdf847e3e356ca8c656/metric/src/freqtrade/connector_status.go#L3

Metric part:
https://github.com/kamontat/fthelper/blob/1f02fdf5ae376261b61b6684a27fde1fc2bcfec9/metric/src/metrics/ft_info.go#L28-L61

**Comment by kamontat** [comment]
> Would like to give it a try to contribute here something, but you're so fast with releasing improvements

If you already similar with [golang](https://golang.org/), first you can start with add some more metrics [here](https://github.com/kamontat/fthelper/tree/main/metric/src/metrics). This ftmetric still lack of some information.

Or if you look for more advance, you can try to implement connection to database itself to get information directly from database. Note that if you working on this, please tell me before starting, so we can have some design first.

**Comment by kamontat** [comment]
By the way, Thank you for your contribute :)
