### ISSUE TITLE
[feature]: Allow multiple postgres database instances

### ISSUE THREAD

**Issue by loewensteinph** [kamontat/fthelper#22]
# Feature request

## Is your feature request related to a problem?

> But be nice to have the ability to specify the postgres database name. 

## Describe the solution you'd like

> FTH_FREQTRADE__DB__URL={hostname}:5432/freqtrade1 <- allow to enter non standard appended "freqtrade" here

## Additional context

> I would like to host multiple bot db's on one postgres instance

**Comment by kamontat** [comment]
You should use `FTH_FREQTRADE_DB_NAME='freqtrade1'`
ref: https://github.com/kamontat/fthelper/blob/main/metric/configs/common.json#L20
