### ISSUE TITLE
[BUG]: hourly/daily/etc performance always empty

### ISSUE THREAD

**Issue by frysee** [kamontat/fthelper#30]
# Bug report

## Describe the bug

No matter how long the scraper runs, the performance metrics are always zero. This applies to all variants of `freqtrade_perf_*`.

## To Reproduce

- Start up with default config. 
- Periodically check prometheus metrics, they all return 0.

## Expected behavior

Working metrics.

## Information

5.0.0beta14

## Additional context

I stepped in via VS Code. SchedulerPerformance::Build is called, but always with empty history. It seems like the performance values are never appended to the cache.

**Comment by kamontat** [comment]
This is expected. I needs to revisit the code, so I disabled it for a moment.
