### ISSUE TITLE
[feature]: Populating initial data on prometheus

### ISSUE THREAD

**Issue by barisengez** [kamontat/fthelper#7]
# Feature request

## Is your feature request related to a problem?

> When ftmetrics+prometheus+grafa is started, there is no initial data for balance and profit calculation

## Describe the solution you'd like

> A way to populate initial data from freqtrade sqlite, so that even after a prometheus data reset, monitoring can continue as before

**Comment by kamontat** [comment]
For strategy performance, I already use APIs data instead of manually calculate in ftmetric, so even first start it should able to get all information from freqtrade itself easier.

For profit calculation per pair also get from APIs.
